### ISSUE TITLE
Move breadcrumbs around

### ISSUE THREAD

**Issue by ProLoser** [hex13/atom-lupa#28]
It doesn't make sense from a hierarchal perspective to put breadcrumbs ABOVE file tabs. Breadcrumbs all exist within the scope of a file. With that in mind, it would make more sent to place them BELOW tabs but above the editor. However, I still feel there's too much risk of confusion between tabs and crumbs. Perhaps you can have an option to place these crumbs into the footer status bar? Or create a second row at the bottom for crumbs?

Additionally, the crumbs are WAY too big. They don't need to take up so much more room.

**Comment by hex13** [comment]
I've added customization in settings. Now user can choose position top/bottom for breadcrumbs.

> Additionally, the crumbs are WAY too big. They don't need to take up so much more room.

its size depends on theme you're using. I've checked few themes I got installed and in Atom Material are really big: 

![image](https://cloud.githubusercontent.com/assets/3883359/19189607/3299cdbc-8c99-11e6-929f-c9e9ffa742af.png)

but in One Dark a little bit smaller:
![image](https://cloud.githubusercontent.com/assets/3883359/19189646/62bb17e4-8c99-11e6-9717-fe1fa3f541c1.png).
(for me this size is good but it's subjective).

Not sure what to do about it. There are many themes for Atom and making fit for one theme might destroy experience in others. But you could adjust CSS styles locally in your Atom stylesheet  ( http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks ) , and write something like this:

``` css
.lupa-breadcrumbs {
    .btn {
        padding: 0 3px;
        line-height: 1em;
        height: 2em;
        font-size: 0.9em;
        max-width: 120px!important;
    }
}

```
